const categories = [
    {
        image: "/categories/Breakfast.png",
        text: "Breakfast",
        bgColorFrom: "#7082461A",
        bgColorTo: "#70824600",
    },
    {
        image: "/categories/Vegan.png",
        text: "Vegan",
        bgColorFrom: "#6CC63F1A",
        bgColorTo: "#6CC63F00",
    },
    {
        image: "/categories/Meat.png",
        text: "Meat",
        bgColorFrom: "#CC261B1A",
        bgColorTo: "#CC261B00",
    },
    {
        image: "/categories/Dessert.png",
        text: "Dessert",
        bgColorFrom: "#F09E001A",
        bgColorTo: "#F09E0000",
    },
    {
        image: "/categories/Lunch.png",
        text: "Lunch",
        bgColorFrom: "#0000000D",
        bgColorTo: "#00000000",
    },
    {
        image: "/categories/Chocolate.png",
        text: "Chocolate",
        bgColorFrom: "#CC261B1A",
        bgColorTo: "#CC261B00",
    },
];

const foodsList = [
    {
        id: "1",
        image: "/foods/food-1.webp",
        imageAlt: "food-1",
        isLike: true,
        title: "Big and Juicy Wagyu Beef Cheeseburger",
        timer: "30 Minutes",
        category: "Snack",
    },
    {
        id: "2",
        image: "/foods/food-2.webp",
        imageAlt: "food-2",
        isLike: false,
        title: "Fresh Lime Roasted Salmon with Ginger Sauce",
        timer: "30 Minutes",
        category: "Fish",
    },
    {
        id: "3",
        image: "/foods/food-3.webp",
        imageAlt: "food-3",
        isLike: false,
        title: "Strawberry Oatmeal Pancake with Honey Syrup",
        timer: "30 Minutes",
        category: "Breakfast",
    },
    {
        id: "4",
        image: "/foods/food-4.webp",
        imageAlt: "food-4",
        isLike: false,
        title: "Fresh and Healthy Mixed Mayonnaise Salad",
        timer: "30 Minutes",
        category: "Healthy",
    },
    {
        id: "5",
        image: "/foods/food-5.webp",
        imageAlt: "food-5",
        isLike: false,
        title: "Chicken Meatballs with Cream Cheese",
        timer: "30 Minutes",
        category: "Meat",
    },
    {
        id: "6",
        image: "/foods/food-6.webp",
        imageAlt: "food-6",
        isLike: false,
        title: "Fruity Pancake with Orange & Blueberry",
        timer: "30 Minutes",
        category: "Sweet",
    },
    {
        id: "7",
        image: "/foods/food-7.webp",
        imageAlt: "food-7",
        isLike: true,
        title: "The Best Easy One Pot Chicken and Rice",
        timer: "30 Minutes",
        category: "Snack",
    },
    {
        id: "8",
        image: "/foods/food-8.webp",
        imageAlt: "food-8",
        isLike: true,
        title: "The Creamiest Creamy Chicken and Bacon Pasta",
        timer: "30 Minutes",
        category: "Noodles",
    },
    {
        id: "9",
        image: "/foods/food-13.webp",
        imageAlt: "food-13",
        isLike: false,
        title: "Mixed Tropical Fruit Salad with Superfood Boosts",
        timer: "30 Minutes",
        category: "Healthy",
    },
    {
        id: "10",
        image: "/foods/food-14.webp",
        imageAlt: "food-14",
        isLike: false,
        title: "Big and Juicy Wagyu Beef Cheeseburger",
        timer: "30 Minutes",
        category: "Western",
    },
    {
        id: "11",
        image: "/foods/food-15.webp",
        imageAlt: "food-15",
        isLike: false,
        title: "Healthy Japanese Fried Rice with Asparagus",
        timer: "30 Minutes",
        category: "Healthy",
    },
    {
        id: "12",
        image: "/foods/food-16.webp",
        imageAlt: "food-16",
        isLike: false,
        title: "Cauliflower Walnut Vegetarian Taco Meat",
        timer: "30 Minutes",
        category: "Eastern",
    },
    {
        id: "13",
        image: "/foods/food-17.webp",
        imageAlt: "food-17",
        isLike: true,
        title: "Rainbow Chicken Salad with Almond Honey Mustard Dressing",
        timer: "30 Minutes",
        category: "Healthy",
    },
    {
        id: "14",
        image: "/foods/food-18.webp",
        imageAlt: "food-18",
        isLike: false,
        title: "Barbeque Spicy Sandwiches with Chips",
        timer: "30 Minutes",
        category: "Snack",
    },
    {
        id: "15",
        image: "/foods/food-19.webp",
        imageAlt: "food-19",
        isLike: false,
        title: "Firecracker Vegan Lettuce Wraps - Spicy!",
        timer: "30 Minutes",
        category: "Seafood",
    },
    {
        id: "16",
        image: "/foods/food-20.webp",
        imageAlt: "food-20",
        isLike: true,
        title: "Chicken Ramen Soup with Mushroom",
        timer: "30 Minutes",
        category: "Japanese",
    },
];

export { categories, foodsList };
